Add mayhem support
mayhemheroes/upx pull request #1
Opened 2022-05-15 22:37 UTC by WGibbs15

- Add test_seed
- Add mayhem support to upx

2022-06-01 22:46 UTC, xansec requested changes
Please do not commit binary files. If you are trying to seed your corpus, you can do this by specifying a tests/testsuite location in the Mayhemfile, or copying your seed file to the `/testsuite` directory in your Dockerfile.

2022-06-01 22:46 UTC, xansec commented on Mayhemfile
> +project: wgibbs15/upx
Please omit the owner name for the project, as this will change after merging.

2022-06-01 22:46 UTC, xansec commented on Mayhemfile
> +image: ghcr.io/wgibbs15/upx-fuzz:latest
You can omit the image name as well.

2022-06-02 00:09 UTC, WGibbs15 commented
Removed the binary file and added cat to /testsuite folder in the dockerfile

2022-06-02 03:21 UTC, xansec commented
Great, LGTM!

2022-06-02 03:21 UTC, merged